# Generated by Django 2.0.3 on 2018-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='main_list_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_num', models.IntegerField(blank=True, null=True)),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Type_of_service', models.CharField(blank=True, max_length=256, null=True)),
                ('Type_of_car', models.CharField(blank=True, max_length=256, null=True)),
                ('Driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Luggage', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Flight_num', models.CharField(blank=True, max_length=100, null=True)),
                ('Start_time', models.DateTimeField(blank=True, null=True)),
                ('End_time', models.DateTimeField(blank=True, null=True)),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('Extra_hours_client', models.TimeField(blank=True, null=True)),
                ('Based_on_client', models.IntegerField(blank=True, null=True)),
                ('Extra_hours_provider', models.TimeField(blank=True, null=True)),
                ('Based_on_provider', models.IntegerField(blank=True, null=True)),
                ('KM', models.IntegerField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True)),
                ('Provider', models.CharField(blank=True, max_length=100, null=True)),
                ('Cost_per_client', models.IntegerField(blank=True, null=True)),
                ('Cost_per_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_extra_hour_client', models.IntegerField(blank=True, null=True)),
                ('Cost_extra_hour_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_transfer_client', models.IntegerField(blank=True, null=True)),
                ('Cost_transfer_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_VIP_client', models.IntegerField(blank=True, null=True)),
                ('Cost_VIP_provider', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('DepOrArr', models.NullBooleanField(choices=[('Dep', 'Dep'), ('Arr', 'Arr')])),
                ('Contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
    ]
