# Generated by Django 2.0.3 on 2018-04-15 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='main_list_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_num', models.IntegerField(blank=True, null=True)),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Type_of_service', models.CharField(blank=True, max_length=256, null=True)),
                ('Type_of_car', models.CharField(blank=True, max_length=256, null=True)),
                ('Driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Luggage', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Flight_num', models.CharField(blank=True, max_length=100, null=True)),
                ('Time_of_flight', models.TimeField(blank=True, null=True)),
                ('Time_of_PU', models.TimeField(blank=True, null=True)),
                ('End_time', models.TimeField(blank=True, null=True)),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('Extra_hours_client', models.TimeField(blank=True, null=True)),
                ('Based_on_client', models.TimeField(blank=True, default='09:00', max_length=256, null=True)),
                ('Extra_hours_provider', models.TimeField(blank=True, null=True)),
                ('Based_on_provider', models.TimeField(blank=True, default='09:00', max_length=256, null=True)),
                ('KM', models.IntegerField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True)),
                ('Provider', models.CharField(blank=True, max_length=100, null=True)),
                ('Cost_per_client', models.IntegerField(blank=True, null=True)),
                ('Cost_per_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_extra_hour_client', models.IntegerField(blank=True, null=True)),
                ('Cost_extra_hour_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_transfer_client', models.IntegerField(blank=True, null=True)),
                ('Cost_transfer_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_VIP_client', models.IntegerField(blank=True, null=True)),
                ('Cost_VIP_provider', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('DepOrArr', models.NullBooleanField(choices=[('Dep', 'Dep'), ('Arr', 'Arr')])),
                ('Contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Proj_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Type_of_car', models.CharField(blank=True, max_length=256, null=True)),
                ('Type_of_service', models.CharField(blank=True, max_length=256, null=True)),
                ('Driver', models.CharField(blank=True, max_length=256, null=True)),
                ('Provider', models.CharField(blank=True, max_length=256, null=True)),
                ('Flight', models.CharField(blank=True, max_length=256, null=True)),
                ('Based_on', models.TimeField(blank=True, default='09:00', max_length=256, null=True)),
                ('Start_time', models.TimeField(blank=True, null=True)),
                ('End_time', models.TimeField(blank=True, null=True)),
                ('Extra_hours', models.TimeField(blank=True, null=True)),
                ('KM', models.IntegerField(blank=True, null=True)),
                ('Extra_KM', models.IntegerField(blank=True, null=True)),
                ('Proj_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proj_parts', to='main.Proj')),
            ],
        ),
        migrations.CreateModel(
            name='Provider_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Provider', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('Customer_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Driver', models.CharField(blank=True, max_length=100, null=True)),
                ('Provider', models.CharField(blank=True, max_length=100, null=True)),
                ('Car', models.CharField(blank=True, max_length=100, null=True)),
                ('Clients_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('DepOrArr', models.NullBooleanField(choices=[('Dep', 'Dep'), ('Arr', 'Arr')])),
                ('Flight', models.CharField(blank=True, max_length=100, null=True)),
                ('Time_of_flight', models.CharField(blank=True, max_length=100, null=True)),
                ('Time_of_PU', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.CharField(blank=True, max_length=100, null=True)),
                ('Project', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
