# Generated by Django 2.0.3 on 2018-06-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Color',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Comments',
            field=models.TextField(blank=True),
        ),
    ]
