# Generated by Django 2.0.3 on 2018-03-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight', models.CharField(blank=True, max_length=256, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Customer_ref_data',
            new_name='Customer_data',
        ),
        migrations.RenameField(
            model_name='customer_data',
            old_name='Customer_ref',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='Service_from_to',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='Time_from_to',
            new_name='From',
        ),
        migrations.AddField(
            model_name='transfer',
            name='DepOrArr',
            field=models.NullBooleanField(choices=[('Dep', 'Dep'), ('Arr', 'Arr')]),
        ),
        migrations.AddField(
            model_name='transfer',
            name='Time_of_PU',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='Time_of_flight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='To',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
