# Generated by Django 2.0.3 on 2018-04-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_client',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_provider',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
