# Generated by Django 2.0.3 on 2018-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_data',
            old_name='Customer',
            new_name='Customer_name',
        ),
        migrations.RenameField(
            model_name='provider_data',
            old_name='Provider',
            new_name='Provider_name',
        ),
        migrations.AddField(
            model_name='customer_data',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer_data',
            name='id_num',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customer_data',
            name='used_a_lot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider_data',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='provider_data',
            name='used_a_lot',
            field=models.BooleanField(default=False),
        ),
    ]
