# Generated by Django 2.0.3 on 2018-04-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_list_model',
            name='Time_of_PU',
        ),
        migrations.RemoveField(
            model_name='main_list_model',
            name='Time_of_flight',
        ),
        migrations.AddField(
            model_name='main_list_model',
            name='Start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='End_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
