# Generated by Django 2.0.3 on 2018-03-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proj',
            old_name='start_date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='proj',
            old_name='proj_name',
            new_name='Proj_name',
        ),
    ]
