# Generated by Django 2.0.3 on 2018-04-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180320_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='main_list_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_num', models.IntegerField(blank=True, null=True)),
                ('Customer', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Type_of_service', models.CharField(blank=True, max_length=256, null=True)),
                ('Type_of_car', models.CharField(blank=True, max_length=256, null=True)),
                ('Driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Luggage', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Flight_num', models.CharField(blank=True, max_length=100, null=True)),
                ('Time_of_flight', models.TimeField(blank=True, null=True)),
                ('Time_of_PU', models.TimeField(blank=True, null=True)),
                ('End_time', models.TimeField(blank=True, null=True)),
                ('From', models.CharField(blank=True, max_length=100, null=True)),
                ('To', models.CharField(blank=True, max_length=100, null=True)),
                ('Extra_hours_client', models.TimeField(blank=True, null=True)),
                ('Based_on_client', models.TimeField(blank=True, default='09:00', max_length=256, null=True)),
                ('Extra_hours_provider', models.TimeField(blank=True, null=True)),
                ('Based_on_provider', models.TimeField(blank=True, default='09:00', max_length=256, null=True)),
                ('KM', models.IntegerField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True)),
                ('Provider', models.CharField(blank=True, max_length=100, null=True)),
                ('Cost_per_client', models.IntegerField(blank=True, null=True)),
                ('Cost_per_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_extra_hour_client', models.IntegerField(blank=True, null=True)),
                ('Cost_extra_hour_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_transfer_client', models.IntegerField(blank=True, null=True)),
                ('Cost_transfer_provider', models.IntegerField(blank=True, null=True)),
                ('Cost_VIP_client', models.IntegerField(blank=True, null=True)),
                ('Cost_VIP_provider', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('DepOrArr', models.NullBooleanField(choices=[('Dep', 'Dep'), ('Arr', 'Arr')])),
                ('Contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
