# Generated by Django 2.0.3 on 2018-05-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180430_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_list_model',
            name='Color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_per_client',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_per_provider',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
