# Generated by Django 2.0.3 on 2018-04-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180416_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Based_on_client',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Based_on_provider',
            field=models.IntegerField(blank=True, max_length=256, null=True),
        ),
    ]
