# Generated by Django 2.0.3 on 2018-07-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180606_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_list_model',
            name='Total_extra_client',
        ),
        migrations.RemoveField(
            model_name='main_list_model',
            name='Total_extra_provider',
        ),
        migrations.AddField(
            model_name='main_list_model',
            name='status_cheshbonit_yeruka1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status חשבונית ירוקה'),
        ),
        migrations.AddField(
            model_name='main_list_model',
            name='status_cheshbonit_yeruka2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status חשבונית ירוקה'),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Customer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference customer'),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Luggage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Number of PAX & Luggage'),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Name client'),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Project_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='Project number'),
        ),
    ]
