# Generated by Django 2.0.3 on 2018-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180314_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_data',
            name='Car',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='customer_ref_data',
            name='Customer_ref',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='driver_data',
            name='Driver',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='model_data',
            name='Model',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='proj',
            name='Proj_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='provider_data',
            name='Provider',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
