# Generated by Django 2.0.3 on 2018-06-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180506_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Color',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
