# Generated by Django 2.0.3 on 2018-07-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180720_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_data',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='id_num',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer_data',
            name='phone_num',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='driver_data',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='driver_data',
            name='id_num',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='driver_data',
            name='phone_num',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='provider_data',
            name='email',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='provider_data',
            name='id_num',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='provider_data',
            name='phone_num',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
