# Generated by Django 2.0.3 on 2018-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180702_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_list_model',
            name='Extra_KM_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main_list_model',
            name='Extra_KM_provider',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
