# Generated by Django 2.0.3 on 2018-04-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180418_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model_data',
            new_name='Service_data',
        ),
    ]
