# Generated by Django 2.0.3 on 2018-03-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_transfer_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='End_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
