# Generated by Django 2.0.3 on 2018-04-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_main_list_model_deporarr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_provider',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
