# Generated by Django 2.0.3 on 2018-03-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180315_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Based_on',
            field=models.TimeField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Extra_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
