# Generated by Django 2.0.3 on 2018-07-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180723_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_per_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_per_provider',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_provider',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
