# Generated by Django 2.0.3 on 2019-03-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180830_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_list_model',
            name='Flight_shcedule',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
