# Generated by Django 2.0.3 on 2019-05-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190501_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Flight_shcedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
