# Generated by Django 2.0.3 on 2019-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190501_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_VIP_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_VIP_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_extra_hour_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_extra_hour_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_per_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_per_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_transfer_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Cost_transfer_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='shonot_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='shonot_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
