# Generated by Django 2.0.3 on 2019-05-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190512_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_list_model',
            old_name='shonot_client',
            new_name='Cost_shonot_client',
        ),
        migrations.RenameField(
            model_name='main_list_model',
            old_name='shonot_provider',
            new_name='Cost_shonot_provider',
        ),
    ]
