# Generated by Django 2.0.3 on 2019-05-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190513_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_list_model',
            name='Project_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project number'),
        ),
    ]
