# Generated by Django 2.0.3 on 2019-07-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190630_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_list_model',
            name='Canceled',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Based_on_client',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Based_on_provider',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_client',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='main_list_model',
            name='Extra_hours_provider',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
